// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkpWOUR4RGpoNmh1UXFmcGs5SEJLNG5DTFdZQnJVVHJIZUwvN3U4S1hVUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMFRPVXhyS0w1NWU3MEJ6R0dWdC9BN1ZxQ1lOUWQ4RWR6UjRXd3k0TDRocz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrSjd3LzNXTDhxYkxDTFRSdVpOVG5iZHd5QUhHbGlSU0hnSGNDeXhlaFhFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXRzFBaExmNm83ZnJNM3VJQ3R5RUhWMm12YUNqSEtCMVJLOW5OOUIxWFUwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhPRXlnVUl6MmdyUEZiU0VadnNWais3Uk5iRHdwWUZNNkpzMXk3WU81WHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVkdGhqbkZwSVpHUCtMNCtGYzE1b3NhZzRwUW0xZDhuUDdmMTl1REZnRGM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0c4S1hnSkQrR0hxWUxZa3g3ekZTL25ORVhQenNXekRpM2lTYUhWZnJXRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic2tQdWJ2NzdZaVhTV0NDSjlaM2p6REU2Wk1VQjdyVlpNYUN2MzRKaE1pRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjNrMnhEQ1hOM1lhTlhFMkZoVjBzakZ1N0R0THAyeS9NUWxaU0h0U0N1MUhQQ09MQmtTQlp0WS9hdCt3K2o4OWZHMVU1UkI1dTNFOUtFbndSUHVJY0RBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDMsImFkdlNlY3JldEtleSI6IlhPOWlTOFowNlF0WU9iQWVyR0ttV3ZpSHlVenBQcGxQWmJCYThvc2MxSVk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IktDOHhIX0JYUUptSm5fUHJSOTE3b3ciLCJwaG9uZUlkIjoiYTI2M2VkM2EtZGViNi00NDFjLThkMzEtMTJiNTdjNjlkNjc3IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlveWNEZytyakxKMmozRy9xNHN3dVFSZDF0WT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsc01Ia0N5aXNPeGQrNzJUN0MvUWMya2FuTG89In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiR1Q5S0pLUDUiLCJtZSI6eyJpZCI6IjIzNDgxNTU4NDkyOTI6NjdAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiTWljayBDb2xlIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKRG41OWNCRUlqL2hyZ0dHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ4MXA3YTQ3VUdGa2Z0R0V0WGlFNDZtZVE0QU51OU42Ry9FamZQYnBLR1QwPSIsImFjY291bnRTaWduYXR1cmUiOiJIZ1pMNXNYcmcvY0NZVVEySkRYcnd6Qlp1S3lTZ1AxMnc2ZklWM0FUbWVhZ1VQVXBUWHZ6VkdFZlpYMmRHKytYcEhsTDJKVGhES3JucUxtZHMybDBDUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoieGNwMGorUW52a2k0SjdiTkFCZEtIdHBYbGZzVnZTUDFiZEVwc1NkYlc4ejFmeCtoVDR5UGhtMk9LcDVVM1Iwd0lpOWYrcW9yMjYxTGw3TUVpYkxzQ1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ4MTU1ODQ5MjkyOjY3QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmNkYWUydU8xQmhaSDdSaExWNGhPT3Bua09BRGJ2VGVodnhJM3oyNlNoazkifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjgxNjc4MzEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUDVPIn0=",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "©Baraka Bega",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "255762190568",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
